server = "OFFICIAL"
cacheLocation = "cache.yaml"
forceLogin = true

[emulator]

[riicConfig]
autoAssigning = true
autoAssignControlCenter = false

[operateConfig]
strategy = "IFF_EXPIRE_SOON"
doFarmAnnihilation = true
doFarmPlan = false
doFarmDaily = true
