# 要登录的服务器，目前仅支持官服（"OFFICIAL"）
服务器: "OFFICIAL"

# 所使用的模拟器，目前只支持 BlueStacks 5
模拟器:
  # 模拟器的安装路径。null 则从注册表中自动寻找
  blueStacksHome: null
  # 模拟器的数据路径。null 则从注册表中自动寻找
  blueStacksData: null

登录配置:
  切换账户: false
  用户名: ""
  密码: ""

# 行动配置
行动配置:
  # 理智使用策略。
  # "WAIT": 不使用任何恢复理智的道具。
  # "POTION": 使用应急理智顶液和应急理智合剂等非源石道具恢复理智。
  # "IFF_EXPIRE_SOON": 仅当即将过期时，使用应急理智顶液和应急理智合剂等非源石道具恢复理智。
  # "ORIGINITE": 使用源石恢复理智。隐含[POTION]，即：优先使用非原石道具，只有当不存在非原石道具时，才会使用源石。
  理智策略: "IFF_EXPIRE_SOON"
  # 是否自动刷剿灭
  刷剿灭: true
  # 是否自动刷“计划”
  刷计划: true
  # 是否自动刷“日常”
  刷日常: true
  资源关种类: "LEVEL_5"

基建配置:
  高级模式: false
  宿舍保留:
    - 2
    - 2
    - 2
    - 0
  无人机房间:
    x: 20
    y: 410
  无人机房间类型: "MANUFACTURE"
  计划:
    - rooms:
        - "B101"
        - "B102"
      schedule:
        - ops:
            - name: "孑"
              elite: 2
              level: 90
            - name: "德克萨斯"
              elite: 2
              level: 90
            - name: "拉普兰德"
              elite: 2
              level: 90
          room: "TRADING"
        - ops:
            - name: "能天使"
              elite: 2
              level: 90
            - name: "海蒂"
              elite: 2
              level: 90
            - name: "空弦"
              elite: 2
              level: 90
          room: "TRADING"
        - ops:
            - name: "月见夜"
              elite: 2
              level: 90
            - name: "空爆"
              elite: 2
              level: 90
            - name: "古米"
              elite: 2
              level: 90
          room: "TRADING"
    - rooms:
        - "B201"
        - "B202"
      schedule:
        - ops:
            - name: "温蒂"
              elite: 2
              level: 90
            - name: "森蚺"
              elite: 2
              level: 90
            - name: "清流"
              elite: 2
              level: 90
          room: "MANUFACTURE"
        - ops:
            - name: "砾"
              elite: 2
              level: 90
            - name: "夜烟"
              elite: 2
              level: 90
            - name: "斑点"
              elite: 2
              level: 90
          room: "MANUFACTURE"
        - ops:
            - name: "远牙"
              elite: 2
              level: 90
            - name: "赫默"
              elite: 2
              level: 90
            - name: "白面鸮"
              elite: 2
              level: 90
          room: "MANUFACTURE"
    - rooms:
        - "B301"
        - "B302"
      schedule:
        - ops:
            - name: "水月"
              elite: 2
              level: 90
            - name: "香草"
              elite: 2
              level: 90
            - name: "史都华德"
              elite: 2
              level: 90
          room: "MANUFACTURE"
        - ops:
            - name: "红云"
              elite: 2
              level: 90
            - name: "黑角"
              elite: 2
              level: 90
            - name: "刻俄柏"
              elite: 2
              level: 90
          room: "MANUFACTURE"
        - ops:
            - name: "红豆"
              elite: 2
              level: 90
            - name: "白雪"
              elite: 2
              level: 90
            - name: "霜叶"
              elite: 2
              level: 90
          room: "MANUFACTURE"