DEBUG: true
emulator: !<top.anagke.auto_ark.adb.Memu>
  location: "C:/Program Files/Microvirt/MEmu/Memu.exe"
arkConfig:
#  loginType: !<top.anagke.auto_ark.ark.ArkLoginContext.BilibiliLogin> {}
  loginType: !<top.anagke.auto_ark.ark.ArkLoginContext.OfficialLogin>
    username: "13046875179"
    password: "F1andiaYingM"
  riicConfig:
    autoAssigning: true
    autoAssignControlCenter: false
  recruitConfig:
    retain6SOperators: true
    retain5SOperators: true
    retain4SOperators: false
  arkOperateConfig:
    strategy: "WAIT"
    isOnEvent: false