DEBUG: false
emulator: !<top.anagke.auto_ark.adb.Memu>
  location: "C:/Program Files/Microvirt/MEmu/Memu.exe"
  adbHost: "127.0.0.1"
  adbPort: 21503
loginConfig:
  loginType: "OFFICIAL"
  username: "13046875179"
  password: "F1andiaYingM"
riicConfig:
  autoAssigning: true
  autoAssignControlCenter: false
recruitConfig:
  retain6SOperators: true
  retain5SOperators: true
  retain4SOperators: false
operateConfig:
  strategy: "POTION"
  isOnEvent: false