# 要登录的服务器，目前仅支持官服（"OFFICIAL"）
服务器: "OFFICIAL"

# 所使用的模拟器，目前只支持 BlueStacks 5
模拟器:
  # 模拟器的安装路径。null 则从注册表中自动寻找
  blueStacksHome: null
  # 模拟器的数据路径。null 则从注册表中自动寻找
  blueStacksData: null

登录配置:
  切换账户: false
  用户名: ""
  密码: ""

# 行动配置
行动配置:
  # 理智使用策略。
  # "WAIT": 不使用任何恢复理智的道具。
  # "POTION": 使用应急理智顶液和应急理智合剂等非源石道具恢复理智。
  # "IFF_EXPIRE_SOON": 仅当即将过期时，使用应急理智顶液和应急理智合剂等非源石道具恢复理智。
  # "ORIGINITE": 使用源石恢复理智。隐含[POTION]，即：优先使用非原石道具，只有当不存在非原石道具时，才会使用源石。
  理智策略: "IFF_EXPIRE_SOON"
  # 是否自动刷剿灭
  刷剿灭: true
  # 是否自动刷“计划”
  刷计划: true
  # 是否自动刷“日常”
  刷日常: true
  资源关种类: "LEVEL_5"

基建配置:
  无人机房间: { x: 55, y: 300 }
  无人机房间类型: 贸易站